---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql-root-password
data:
  password: bXktc3VwZXItc2VjcmV0LXBhc3M=
---
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: mysql-wordpress
spec:
  replicas: 3
  secretRef:
    name: wordpress-mysql-root-password
